kind = "api"
previewPath = "/"
title = "Tic Tac Toe AI"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "Tic Tac Toe Server"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]

[services.production.run]
args = ["node", "artifacts/api-server/server.js"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/healthz"
